/**
 * Database schema — the single source of truth for both the SQL migrations
 * (generated by drizzle-kit) and the TypeScript types used across the backend.
 *
 * Design rationale lives in docs/DESIGN.md §3. The decisions worth remembering:
 *   - `users` (authentication identity) is separate from `employees` (HR record),
 *     so a password hash never sits in a table that business queries read.
 *   - Nothing is hard-deleted. People are TERMINATED, departments and positions
 *     are deactivated — attendance and leave history has to survive.
 *   - Date-only columns use `mode: 'string'` ("2026-03-14"). A JS Date would drag
 *     a timezone into a question that has no time in it, which is how "checked in
 *     on the 14th" becomes "the 13th" for anyone east of UTC.
 *   - Business rules that a constraint can express are expressed as constraints.
 *     The database is the last line of defence, and it does not have bugs in the
 *     way application code does.
 */

import { relations, sql } from 'drizzle-orm';
import {
  boolean,
  check,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const roleEnum = pgEnum('role', ['ADMIN', 'HR', 'EMPLOYEE']);
export const genderEnum = pgEnum('gender', ['MALE', 'FEMALE', 'OTHER']);
export const employmentStatusEnum = pgEnum('employment_status', [
  'PROBATION',
  'ACTIVE',
  'ON_LEAVE',
  'TERMINATED',
]);
export const positionLevelEnum = pgEnum('position_level', [
  'INTERN',
  'JUNIOR',
  'MID',
  'SENIOR',
  'LEAD',
  'MANAGER',
]);
export const attendanceStatusEnum = pgEnum('attendance_status', ['PRESENT', 'LATE', 'ON_LEAVE']);
export const leaveStatusEnum = pgEnum('leave_status', [
  'PENDING',
  'APPROVED',
  'REJECTED',
  'CANCELLED',
]);
export const aiMessageRoleEnum = pgEnum('ai_message_role', ['USER', 'ASSISTANT']);

const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
};

// ---------------------------------------------------------------------------
// Identity
// ---------------------------------------------------------------------------

export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    email: varchar('email', { length: 255 }).notNull(),
    passwordHash: varchar('password_hash', { length: 255 }).notNull(),
    role: roleEnum('role').notNull().default('EMPLOYEE'),
    isActive: boolean('is_active').notNull().default(true),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    ...timestamps,
  },
  (t) => [
    // Emails are compared case-insensitively at login, so uniqueness must be
    // case-insensitive too — otherwise "Anna@x.com" and "anna@x.com" are two
    // accounts that both answer to the same login.
    uniqueIndex('users_email_lower_unique').on(sql`lower(${t.email})`),
    index('users_role_idx').on(t.role),
  ],
);

export const refreshTokens = pgTable(
  'refresh_tokens',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** SHA-256 of the token. The raw value is never stored: if this table leaks,
     *  what leaks is useless — the same reasoning as hashing passwords. */
    tokenHash: varchar('token_hash', { length: 64 }).notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    /** Set when this token is rotated. Presenting a token that has already been
     *  replaced means someone is replaying a stolen token — see auth.service. */
    replacedByHash: varchar('replaced_by_hash', { length: 64 }),
    userAgent: varchar('user_agent', { length: 255 }),
    ipAddress: varchar('ip_address', { length: 64 }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('refresh_tokens_hash_unique').on(t.tokenHash),
    index('refresh_tokens_user_idx').on(t.userId),
    index('refresh_tokens_expires_idx').on(t.expiresAt),
  ],
);

// ---------------------------------------------------------------------------
// Organisation
// ---------------------------------------------------------------------------

export const departments = pgTable(
  'departments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    code: varchar('code', { length: 16 }).notNull().unique(),
    name: varchar('name', { length: 120 }).notNull().unique(),
    description: varchar('description', { length: 500 }),
    isActive: boolean('is_active').notNull().default(true),
    ...timestamps,
  },
  (t) => [index('departments_active_idx').on(t.isActive)],
);

export const positions = pgTable(
  'positions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    title: varchar('title', { length: 120 }).notNull().unique(),
    level: positionLevelEnum('level').notNull().default('JUNIOR'),
    description: varchar('description', { length: 500 }),
    isActive: boolean('is_active').notNull().default(true),
    ...timestamps,
  },
  (t) => [index('positions_active_idx').on(t.isActive)],
);

export const employees = pgTable(
  'employees',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    /** 1:1 with users. `restrict`, not `cascade`: accounts are deactivated,
     *  never deleted, and dropping the employee row would orphan years of
     *  attendance history. */
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    employeeCode: varchar('employee_code', { length: 20 }).notNull().unique(),
    firstName: varchar('first_name', { length: 80 }).notNull(),
    lastName: varchar('last_name', { length: 80 }).notNull(),
    phone: varchar('phone', { length: 20 }),
    dateOfBirth: date('date_of_birth', { mode: 'string' }),
    gender: genderEnum('gender'),
    address: varchar('address', { length: 255 }),
    hireDate: date('hire_date', { mode: 'string' }).notNull(),
    /** `restrict`: you cannot delete a department that still has employees.
     *  The database enforces it even when application code forgets to. */
    departmentId: uuid('department_id').references(() => departments.id, {
      onDelete: 'restrict',
    }),
    positionId: uuid('position_id').references(() => positions.id, { onDelete: 'restrict' }),
    employmentStatus: employmentStatusEnum('employment_status').notNull().default('PROBATION'),
    /** Never returned to an EMPLOYEE caller for anyone but themselves, and never
     *  reachable through any AI tool. See docs/DESIGN.md §4 and §6. */
    baseSalary: numeric('base_salary', { precision: 12, scale: 2 }).notNull().default('0'),
    terminatedAt: timestamp('terminated_at', { withTimezone: true }),
    ...timestamps,
  },
  (t) => [
    uniqueIndex('employees_user_unique').on(t.userId),
    index('employees_department_idx').on(t.departmentId),
    index('employees_position_idx').on(t.positionId),
    index('employees_status_idx').on(t.employmentStatus),
    index('employees_name_idx').on(t.lastName, t.firstName),
    check('employees_salary_non_negative', sql`${t.baseSalary} >= 0`),
    // A terminated employee must have a termination date, and an employee who is
    // not terminated must not. Two columns that can disagree are two columns that
    // eventually will.
    check(
      'employees_termination_consistent',
      sql`(${t.employmentStatus} = 'TERMINATED') = (${t.terminatedAt} IS NOT NULL)`,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Attendance
// ---------------------------------------------------------------------------

export const attendanceRecords = pgTable(
  'attendance_records',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    employeeId: uuid('employee_id')
      .notNull()
      .references(() => employees.id, { onDelete: 'cascade' }),
    /** A calendar day, not an instant. The unique constraint below depends on
     *  this being day-precision. */
    workDate: date('work_date', { mode: 'string' }).notNull(),
    checkInAt: timestamp('check_in_at', { withTimezone: true }),
    checkOutAt: timestamp('check_out_at', { withTimezone: true }),
    status: attendanceStatusEnum('status').notNull().default('PRESENT'),
    lateMinutes: integer('late_minutes').notNull().default(0),
    earlyLeaveMinutes: integer('early_leave_minutes').notNull().default(0),
    workMinutes: integer('work_minutes').notNull().default(0),
    overtimeMinutes: integer('overtime_minutes').notNull().default(0),
    note: varchar('note', { length: 255 }),
    /** Audit trail for HR corrections: who changed this record, and when. */
    correctedById: uuid('corrected_by_id').references(() => users.id, { onDelete: 'set null' }),
    correctedAt: timestamp('corrected_at', { withTimezone: true }),
    ...timestamps,
  },
  (t) => [
    // THE constraint of this module: one attendance row per person per day.
    // An application-level "does a record already exist?" check loses the race
    // between two concurrent check-in requests. A unique index cannot.
    uniqueIndex('attendance_employee_date_unique').on(t.employeeId, t.workDate),
    index('attendance_work_date_idx').on(t.workDate),
    index('attendance_status_idx').on(t.status),
    check(
      'attendance_checkout_after_checkin',
      sql`${t.checkOutAt} IS NULL OR ${t.checkInAt} IS NULL OR ${t.checkOutAt} > ${t.checkInAt}`,
    ),
    check(
      'attendance_minutes_non_negative',
      sql`${t.lateMinutes} >= 0 AND ${t.earlyLeaveMinutes} >= 0 AND ${t.workMinutes} >= 0 AND ${t.overtimeMinutes} >= 0`,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Leave
// ---------------------------------------------------------------------------

export const leaveTypes = pgTable('leave_types', {
  id: uuid('id').primaryKey().defaultRandom(),
  code: varchar('code', { length: 16 }).notNull().unique(),
  name: varchar('name', { length: 80 }).notNull().unique(),
  description: varchar('description', { length: 255 }),
  /** Days granted per employee per year when a balance row is created. */
  defaultDays: integer('default_days').notNull().default(0),
  isPaid: boolean('is_paid').notNull().default(true),
  isActive: boolean('is_active').notNull().default(true),
  ...timestamps,
});

export const leaveBalances = pgTable(
  'leave_balances',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    employeeId: uuid('employee_id')
      .notNull()
      .references(() => employees.id, { onDelete: 'cascade' }),
    leaveTypeId: uuid('leave_type_id')
      .notNull()
      .references(() => leaveTypes.id, { onDelete: 'restrict' }),
    year: integer('year').notNull(),
    entitledDays: integer('entitled_days').notNull().default(0),
    usedDays: integer('used_days').notNull().default(0),
    ...timestamps,
  },
  (t) => [
    // One balance row per employee, per leave type, per year. A duplicate row
    // silently hands the employee a second allowance.
    uniqueIndex('leave_balance_unique').on(t.employeeId, t.leaveTypeId, t.year),
    // The database refuses to let used days exceed the entitlement, whatever the
    // service layer believes. This is what makes the transaction in
    // leave.service.ts safe against a concurrent double approval.
    check(
      'leave_balance_within_entitlement',
      sql`${t.usedDays} >= 0 AND ${t.usedDays} <= ${t.entitledDays}`,
    ),
  ],
);

export const leaveRequests = pgTable(
  'leave_requests',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    employeeId: uuid('employee_id')
      .notNull()
      .references(() => employees.id, { onDelete: 'cascade' }),
    leaveTypeId: uuid('leave_type_id')
      .notNull()
      .references(() => leaveTypes.id, { onDelete: 'restrict' }),
    startDate: date('start_date', { mode: 'string' }).notNull(),
    endDate: date('end_date', { mode: 'string' }).notNull(),
    /** Working days only — weekends are excluded when the request is created. */
    totalDays: integer('total_days').notNull(),
    reason: varchar('reason', { length: 500 }).notNull(),
    status: leaveStatusEnum('status').notNull().default('PENDING'),
    decidedById: uuid('decided_by_id').references(() => users.id, { onDelete: 'set null' }),
    decidedAt: timestamp('decided_at', { withTimezone: true }),
    decisionNote: varchar('decision_note', { length: 500 }),
    ...timestamps,
  },
  (t) => [
    index('leave_requests_status_idx').on(t.status),
    index('leave_requests_employee_start_idx').on(t.employeeId, t.startDate),
    index('leave_requests_range_idx').on(t.startDate, t.endDate),
    check('leave_dates_ordered', sql`${t.endDate} >= ${t.startDate}`),
    check('leave_total_days_positive', sql`${t.totalDays} > 0`),
    // A decided request must record who decided it and when; a pending one must
    // not pretend it was decided.
    check(
      'leave_decision_consistent',
      sql`(${t.status} IN ('APPROVED', 'REJECTED')) = (${t.decidedAt} IS NOT NULL)`,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Audit
// ---------------------------------------------------------------------------

export const auditLogs = pgTable(
  'audit_logs',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
    action: varchar('action', { length: 80 }).notNull(),
    entityType: varchar('entity_type', { length: 60 }).notNull(),
    entityId: varchar('entity_id', { length: 64 }),
    metadata: jsonb('metadata'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('audit_actor_idx').on(t.actorUserId, t.createdAt),
    index('audit_entity_idx').on(t.entityType, t.entityId),
  ],
);

// ---------------------------------------------------------------------------
// AI assistant
// ---------------------------------------------------------------------------

export const aiConversations = pgTable(
  'ai_conversations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    title: varchar('title', { length: 160 }).notNull(),
    ...timestamps,
  },
  (t) => [index('ai_conversations_user_idx').on(t.userId, t.updatedAt)],
);

export const aiMessages = pgTable(
  'ai_messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    conversationId: uuid('conversation_id')
      .notNull()
      .references(() => aiConversations.id, { onDelete: 'cascade' }),
    role: aiMessageRoleEnum('role').notNull(),
    content: text('content').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('ai_messages_conversation_idx').on(t.conversationId, t.createdAt)],
);

/**
 * Every tool the model asked for, whether or not it was allowed to run.
 * This table is what turns "the AI cannot escalate privileges" from a claim
 * into something you can query.
 */
export const aiToolInvocations = pgTable(
  'ai_tool_invocations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    messageId: uuid('message_id').references(() => aiMessages.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    toolName: varchar('tool_name', { length: 80 }).notNull(),
    arguments: jsonb('arguments').notNull(),
    allowed: boolean('allowed').notNull(),
    deniedReason: varchar('denied_reason', { length: 255 }),
    durationMs: integer('duration_ms'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('ai_tool_user_idx').on(t.userId, t.createdAt),
    index('ai_tool_name_allowed_idx').on(t.toolName, t.allowed),
  ],
);

// ---------------------------------------------------------------------------
// Relations — used by Drizzle's relational query API so that "employee with
// department and position" is one SQL statement rather than three round trips.
// ---------------------------------------------------------------------------

export const usersRelations = relations(users, ({ one, many }) => ({
  employee: one(employees, { fields: [users.id], references: [employees.userId] }),
  refreshTokens: many(refreshTokens),
  aiConversations: many(aiConversations),
}));

export const refreshTokensRelations = relations(refreshTokens, ({ one }) => ({
  user: one(users, { fields: [refreshTokens.userId], references: [users.id] }),
}));

export const departmentsRelations = relations(departments, ({ many }) => ({
  employees: many(employees),
}));

export const positionsRelations = relations(positions, ({ many }) => ({
  employees: many(employees),
}));

export const employeesRelations = relations(employees, ({ one, many }) => ({
  user: one(users, { fields: [employees.userId], references: [users.id] }),
  department: one(departments, {
    fields: [employees.departmentId],
    references: [departments.id],
  }),
  position: one(positions, { fields: [employees.positionId], references: [positions.id] }),
  attendanceRecords: many(attendanceRecords),
  leaveRequests: many(leaveRequests),
  leaveBalances: many(leaveBalances),
}));

export const attendanceRecordsRelations = relations(attendanceRecords, ({ one }) => ({
  employee: one(employees, {
    fields: [attendanceRecords.employeeId],
    references: [employees.id],
  }),
  correctedBy: one(users, {
    fields: [attendanceRecords.correctedById],
    references: [users.id],
  }),
}));

export const leaveTypesRelations = relations(leaveTypes, ({ many }) => ({
  leaveRequests: many(leaveRequests),
  leaveBalances: many(leaveBalances),
}));

export const leaveBalancesRelations = relations(leaveBalances, ({ one }) => ({
  employee: one(employees, { fields: [leaveBalances.employeeId], references: [employees.id] }),
  leaveType: one(leaveTypes, {
    fields: [leaveBalances.leaveTypeId],
    references: [leaveTypes.id],
  }),
}));

export const leaveRequestsRelations = relations(leaveRequests, ({ one }) => ({
  employee: one(employees, { fields: [leaveRequests.employeeId], references: [employees.id] }),
  leaveType: one(leaveTypes, {
    fields: [leaveRequests.leaveTypeId],
    references: [leaveTypes.id],
  }),
  decidedBy: one(users, { fields: [leaveRequests.decidedById], references: [users.id] }),
}));

export const aiConversationsRelations = relations(aiConversations, ({ one, many }) => ({
  user: one(users, { fields: [aiConversations.userId], references: [users.id] }),
  messages: many(aiMessages),
}));

export const aiMessagesRelations = relations(aiMessages, ({ one, many }) => ({
  conversation: one(aiConversations, {
    fields: [aiMessages.conversationId],
    references: [aiConversations.id],
  }),
  toolInvocations: many(aiToolInvocations),
}));

export const aiToolInvocationsRelations = relations(aiToolInvocations, ({ one }) => ({
  message: one(aiMessages, {
    fields: [aiToolInvocations.messageId],
    references: [aiMessages.id],
  }),
  user: one(users, { fields: [aiToolInvocations.userId], references: [users.id] }),
}));

// ---------------------------------------------------------------------------
// Inferred types — every layer above uses these, so a schema change surfaces as
// a type error rather than as a runtime surprise.
// ---------------------------------------------------------------------------

export type Role = (typeof roleEnum.enumValues)[number];
export type EmploymentStatus = (typeof employmentStatusEnum.enumValues)[number];
export type AttendanceStatus = (typeof attendanceStatusEnum.enumValues)[number];
export type LeaveStatus = (typeof leaveStatusEnum.enumValues)[number];

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Employee = typeof employees.$inferSelect;
export type NewEmployee = typeof employees.$inferInsert;
export type Department = typeof departments.$inferSelect;
export type Position = typeof positions.$inferSelect;
export type AttendanceRecord = typeof attendanceRecords.$inferSelect;
export type LeaveType = typeof leaveTypes.$inferSelect;
export type LeaveBalance = typeof leaveBalances.$inferSelect;
export type LeaveRequest = typeof leaveRequests.$inferSelect;
