import type { LlmChatRequest, LlmChatResponse, LlmError, LlmProvider } from './types.js';

/**
 * A provider that never leaves the process.
 *
 * Two jobs:
 *
 *  1. **Tests.** Every AI test — including the security ones — needs the model
 *     to make a *specific* tool call so the assertion is about the authorization
 *     layer rather than about what a real model felt like doing today. `script`
 *     makes each response deterministic. This is the reason the AI features are
 *     testable at all, and the main practical payoff of the provider interface.
 *
 *  2. **Running the app with no API key.** `AI_PROVIDER=fake` gives a working
 *     assistant that answers a handful of questions with real database data via
 *     real tool calls, so a reviewer can clone the repository and see the whole
 *     pipeline work without signing up for anything.
 *
 * It is not a model. Question matching is keyword-based, and it says so.
 */
export class FakeLlmProvider implements LlmProvider {
  readonly name = 'fake';

  private queue: LlmChatResponse[] = [];
  private failWith: LlmError | null = null;

  /** Queue exact responses, consumed in order. Used by tests. */
  script(...responses: LlmChatResponse[]): this {
    this.queue.push(...responses);
    return this;
  }

  /** Make the next call fail, to exercise the error paths. */
  failNext(error: LlmError): this {
    this.failWith = error;
    return this;
  }

  reset(): this {
    this.queue = [];
    this.failWith = null;
    return this;
  }

  async chat(request: LlmChatRequest): Promise<LlmChatResponse> {
    if (this.failWith) {
      const error = this.failWith;
      this.failWith = null;
      throw error;
    }

    const scripted = this.queue.shift();
    if (scripted) return scripted;

    return this.improvise(request);
  }

  /**
   * Keyword routing, used only when nothing is scripted.
   *
   * Note what it still does correctly: it *calls the tools*. The request goes
   * through the same authorization, validation and audit path as a real model's
   * would, so the demo exercises the security layer rather than bypassing it.
   */
  private improvise(request: LlmChatRequest): LlmChatResponse {
    const lastToolMessage = [...request.messages]
      .reverse()
      .find((message) => message.role === 'tool');

    // A tool has already run: summarise its result instead of calling again.
    if (lastToolMessage && lastToolMessage.role === 'tool') {
      return {
        content:
          `Here is what I found from \`${lastToolMessage.name}\`:\n\n` +
          '```json\n' +
          lastToolMessage.content.slice(0, 1200) +
          '\n```\n\n' +
          '_(Offline demo mode: this summary is generated by a stub, not by a language ' +
          'model. The data above is real — it came from the database through an ' +
          'authorized tool call.)_',
        toolCalls: [],
      };
    }

    const lastUser = [...request.messages].reverse().find((message) => message.role === 'user');
    const question = lastUser && lastUser.role === 'user' ? lastUser.content.toLowerCase() : '';

    const available = new Set(request.tools.map((tool) => tool.name));
    const today = new Date().toISOString().slice(0, 10);
    const monthStart = `${today.slice(0, 7)}-01`;

    const route = (name: string, args: Record<string, unknown> = {}) =>
      available.has(name)
        ? {
            content: null,
            toolCalls: [{ id: `fake_${name}`, name, arguments: args }],
          }
        : null;

    const has = (...keywords: string[]) => keywords.some((word) => question.includes(word));
    const mine = has('my ', 'i have', 'do i', 'me ', 'của tôi', 'tôi');

    const aboutLeave = has('leave', 'holiday', 'nghỉ', 'phép');
    const aboutBalance = has('balance', 'left', 'remaining', 'còn', 'entitle');
    const aboutAttendance = has('attendance', 'check-in', 'checked in', 'chấm công', 'late', 'muộn');

    const candidate =
      // Personal questions first: "how many days of leave do I have left?"
      (aboutLeave && aboutBalance && route('get_my_leave_balance')) ||
      (aboutLeave && mine && has('request', 'đơn') && route('get_my_leave_requests')) ||
      (aboutAttendance && mine && route('get_my_attendance_summary')) ||
      // Organisation-wide questions (only routed if the role has the tool).
      (has('pending', 'chờ duyệt', 'awaiting', 'approval') &&
        route('get_pending_leave_requests')) ||
      (has('late', 'đi muộn') && route('get_late_employees', { from: monthStart, to: today })) ||
      (has('department', 'phòng ban', 'per team', 'each team') &&
        route('get_department_headcount')) ||
      (has('how many employees', 'headcount', 'bao nhiêu nhân viên', 'total employees', 'work here') &&
        route('get_headcount')) ||
      (aboutLeave && has('statistic', 'thống kê', 'report') &&
        route('get_leave_statistics', { from: monthStart, to: today })) ||
      (aboutAttendance && has('statistic', 'thống kê', 'report') &&
        route('get_attendance_statistics', { from: monthStart, to: today })) ||
      (has('search', 'find employee', 'tìm nhân viên', 'who is') &&
        route('search_employees', { query: '' })) ||
      // Fall back to the personal tools, which every role has.
      (aboutLeave && route('get_my_leave_balance')) ||
      (aboutAttendance && route('get_my_attendance_summary'));

    if (candidate) return candidate;

    return {
      content:
        'I am running in offline demo mode (`AI_PROVIDER=fake`), so I can only answer a ' +
        'few example questions. Try:\n\n' +
        '- "How many days of leave do I have left?"\n' +
        '- "What is my attendance summary this month?"\n' +
        '- "How many pending leave requests are there?" (HR/Admin)\n' +
        '- "Who was late this month?" (HR/Admin)\n' +
        '- "How many employees are in each department?" (HR/Admin)\n\n' +
        'Set `AI_PROVIDER=openai` or `anthropic` with an API key for real answers.',
      toolCalls: [],
    };
  }
}
